//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 DIPYS.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_DIPYSTYPE                   130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_SAMPLING             310
#define IDC_EDIT_YSTEP                  1000
#define IDC_EDIT_XSTEP                  1001
#define yStep                           1002
#define xStep                           1003
#define IDC_EDIT_Z                      1004
#define ID_DIGITIZE_SUBSAMPLING         32771
#define ID_DIGITIZE_MOSAIC              32772
#define ID_DIGITIZE_QUANTIZERULE        32773
#define ID_DIGITIZE_QUANTIZE            32774
#define ID_COLOR_RED                    32775
#define ID_COLOR_GREEN                  32776
#define ID_COLOR_BLUE                   32777
#define ID_COLOR_BGR                    32778
#define ID_COLOR_CYAN                   32779
#define ID_COLOR_MAGENTA                32780
#define ID_COLOR_YELLOW                 32781
#define ID_COLOR_LAB                    32782
#define ID_COLOR_LIGHTNESS              32783
#define ID_COLOR_A                      32784
#define ID_COLOR_B                      32785
#define ID_COLOR_HSV                    32786
#define ID_COLOR_HUE                    32787
#define ID_COLOR_SATURATION             32788
#define ID_COLOR_VALUE                  32789
#define ID_COLOR_HUEADD                 32790
#define ID_GRAY_MIN                     32791
#define ID_COLORIZE_JET                 32792
#define ID_COLORIZE_BONE                32793
#define ID_COLORIZE_HSV                 32794
#define ID_GRAY_MAX                     32795
#define ID_ARITHMETIC_ADD               32796
#define ID_ARITHMETIC_SUBTRACT          32797
#define ID_ARITHMETIC_MULTIPLY          32798
#define ID_ARITHMETIC_DIVIDE            32799
#define ID_ARITHMETIC_LINEARBURN        32800
#define ID_ARITHMETIC_SCREEN            32801
#define ID_ARITHMETIC_EXCLUSION         32802
#define ID_ARITHMETIC_DIFFERENCE        32803
#define ID_ARITHMETIC_NEGATIVE          32804
#define ID_ARITHMETIC_COLORDODGE        32805
#define ID_ARITHMETIC_COLORBURN         32806
#define ID_GRAY_ONGRAYMIDDLE            32807
#define ID_GRAY_MIDDLE                  32808
#define ID_GRAY_WEIGHTEDAVERAGEHSV      32809
#define ID_GRAY_COMPOUNDFORL            32810
#define ID_ARITHMETIC_ALPHA             32811
#define ID_ARITHMETIC_MULTIPLYALPHA     32812
#define ID_ARITHMETIC_OVERLAY           32813
#define ID_ARITHMETIC_HARDLIGHT         32814
#define ID_ARITHMETIC_VIVIDLIGHT        32815
#define ID_ARITHMETIC_LINEARLIGHT       32816
#define ID_ARITHMETIC_HUE               32817
#define ID_ARITHMETIC_SATURATION        32818
#define ID_ARITHMETIC_LUMINOSITY        32819
#define ID_ARITHMETIC_COLOR             32820
#define ID_LOGIC_MIN                    32821
#define ID_LOGIC_MAX                    32822
#define ID_LOGIC_PINLIGHT               32823
#define ID_LOGIC_AND                    32824
#define ID_LOGIC_OR                     32825
#define ID_LOGIC_NOT                    32826
#define ID_LOGIC_XOR                    32827
#define ID_LOGIC_NAND                   32828
#define ID_LOGIC_NOR                    32829
#define ID_LOGIC_COMPAREAND             32830
#define ID_LOGIC_COMPAREOR              32831
#define ID_LOGIC_COMPAREXOR             32832
#define ID_GEOMETRY_TRANSLATE           32833
#define ID_GEOMETRY_TRANSLATESCALE      32834
#define ID_GEOMETRY_TRANSLATEAFFINE     32835
#define ID_GEOMETRY_SCALENEAREST        32836
#define ID_GEOMETRY_SCALEBILINEAR       32837
#define ID_GEOMETRY_SCALEBICUBIC        32838
#define ID_GEOMETRY_SCALEBILINEAREXACT  32839
#define ID_GEOMETRY_ROTATE90            32840
#define ID_GEOMETRY_CLOCKWISE           32841
#define ID_GEOMETRY_ROTATE270           32842
#define ID_GEOMETRY_ROTATE              32843
#define ID_GEOMETRY_ROTATESCALE         32844
#define ID_GEOMETRY_SHEAR               32845
#define ID_GEOMETRY_AFFINE              32846
#define ID_GEOMETRY_MIRROR              32847
#define ID_GEOMETRY_MIRRORVERTICAL      32848
#define ID_GEOMETRY_MIRRORCOMEPLETELY   32849
#define ID_GEOMETRY_TRANSPOSE           32850
#define ID_GEOMETRY_PERSPECTIVE         32851
#define ID_GEOMETRY_POINTS              32852
#define ID_GEOMETRY_TWIRL               32853
#define ID_GEOMETRY_RIPPLE              32854
#define ID_GEOMETRY_SPHERICAL           32855
#define ID_GEOMETRY_STITCH              32856
#define ID_POINT_BRIGHTNESSMAT          32857
#define ID_POINT_BRIGHTNESS             32858
#define ID_POINT_CONTRASTMAT            32859
#define ID_POINT_CONTRAST               32860
#define ID_POINT_AUTOCONTRAST           32861
#define ID_POINT_GLOBALMAT              32862
#define ID_POINT_GLOBAL                 32863
#define ID_POINT_LOCAL                  32864
#define ID_POINT_PIECEWISE              32865
#define ID_POINT_LOGARITHMIC            32866
#define ID_POINT_EXPONENT               32867
#define ID_POINT_POWER                  32868
#define ID_POINT_BLACKWHITE             32869
#define ID_POINT_PRESERVE               32870
#define ID_POINT_BIT                    32871
#define ID_POINT_AUTOCONTRASTMAT        32872
#define ID_HISTOGRAM_COMPUTE            32873
#define ID_HISTOGRAM_DRAW               32874
#define ID_HISTOGRAM_CUMULATECOMPUTE    32875
#define ID_HISTOGRAM_CUMULATEDRAW       32876
#define ID_HISTOGRAM_BIN                32877
#define ID_HISTOGRAM_EQUALIZE           32878
#define ID_HISTOGRAM_MATCH              32879
#define ID_HISTOGRAM_STEP               32880
#define ID_HISTOGRAM_GAUSSIAN           32881

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        312
#define _APS_NEXT_COMMAND_VALUE         32882
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
